my:
  custom:
    property: Hello from application properties

spring:
  application:
    name: danmak

init:
  custom:
    property: false

custom:
  login-url: test-login
  credentials:
      user: test-user
      password: pass